/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-portable_interrogator_blocks
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_PORTABLE_INTERROGATOR_BLOCKS_API_H
#define INCLUDED_PORTABLE_INTERROGATOR_BLOCKS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_portable_interrogator_blocks_EXPORTS
#define PORTABLE_INTERROGATOR_BLOCKS_API __GR_ATTR_EXPORT
#else
#define PORTABLE_INTERROGATOR_BLOCKS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PORTABLE_INTERROGATOR_BLOCKS_API_H */
